name: test_bottom_navigation_bar
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  animated_splash_screen: ^1.3.0
  google_maps: ^6.2.0
  cupertino_icons: ^1.0.2
  webview_flutter: ^3.0.2
  http: ^0.13.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true



  assets:
    - images/
    - jsonfile/


  fonts:
    - family: Noto
      fonts:
        - asset: fonts/NotoSansArabic.ttf

    - family: Bachra
      fonts:
        - asset: fonts/ArslanWessam.ttf




